Repository netmeld/netmeld, pull requests merged in 2020-08, with the labels that each got.

#36 Headless playbook execution using tmux
  playbook/CMakeLists.txt
  playbook/nmdb-playbook/CommandRunnerSingleton.cpp
  playbook/nmdb-playbook/CommandRunnerSingleton.hpp
  playbook/nmdb-playbook/nmdb-playbook.cpp
Labels: Enhancement

#39 Show mac updates
  cmake/BuildHelpers.cmake
  datastore/importers/nmdb-import-show-mac-address-table/CMakeLists.txt
  datastore/importers/nmdb-import-show-mac-address-table/Parser.cpp
  datastore/importers/nmdb-import-show-mac-address-table/Parser.hpp
  datastore/importers/nmdb-import-show-mac-address-table/Parser.test.cpp
Labels: Bug

#40 Enhanced support for show cdp import tool.
  datastore/importers/nmdb-import-show-cdp-neighbor/CMakeLists.txt
  datastore/importers/nmdb-import-show-cdp-neighbor/Parser.cpp
  datastore/importers/nmdb-import-show-cdp-neighbor/Parser.hpp
  datastore/importers/nmdb-import-show-cdp-neighbor/Parser.test.cpp
Labels: Enhancement, TODO
